- hosts: all
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/adcuratio/core-backend/
      dest: "/home/ubuntu/adcuratio/core-backend/"
      clone: yes
      update: yes
