# ---
# - name: Create a virtual environment and set up the alias
#   hosts: localhost
#   become: yes

#   vars:
#     user_name: "deeksha"
#     environment_name: "env"
#     project_path: "/home/{{ user_name }}/adcuratio"
#     virtualenv_path: "{{ project_path }}/{{ environment_name }}"
#     alias_command: "alias adc='export SERVER_NAME=MASTER && export SERVER_DESC=MASTER && export DEBUG=true && export OPERATOR_ID=1 && source {{ virtualenv_path }}/bin/activate && cd {{ project_path }}/core-backend/'"

#   tasks:
#     - name: Install virtualenv package
#       pip:
#         name: virtualenv
#         state: present

#     - name: Create the virtual environment using virtualenv
#       command: "virtualenv {{ virtualenv_path }}"
#       args:
#         creates: "{{ virtualenv_path }}/bin/activate"

#     - name: Add the alias to .bashrc
#       lineinfile:
#         path: "/home/{{ user_name }}/.bashrc"
#         line: "{{ alias_command }}"
#         create: yes

#     - name: Set the alias for the current session
#       shell: "{{ alias_command }}"


# ---
- hosts: all
  gather_facts: no
  become: yes
  # become_method: sudo
  # vars:
  #   ansible_become_password: pass

  tasks:
  # - name: Download pip installer
  #   get_url:
  #     url: https://bootstrap.pypa.io/get-pip.py
  #     dest: /tmp/get-pip.py
  # - name: Install pip
  #   shell: |
  #     /usr/bin/python /tmp/get-pip.py
  - 
  - name: Install virtualenv module
    pip:
      name: virtualenv
      state: latest
  - name: Create virtualenv for adcuratio
    pip:
      name: deeksha
      state: latest
      virtualenv: /home/deeksha/setup-automation/adcuratio/env