---
- hosts: all
  gather_facts: no
  become: yes
 
  tasks:
  
  - name: Install virtualenv module
    pip:
      name: env
      state: latest
  - name: Create virtualenv for adcuratio
    pip:
      name: deeksha
      state: latest
      virtualenv: /home/deeksha/setup-automation/adcuratio/env