---
- name: Create and set up Python Virtual Environment
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: pass


    user_name: "deeksha"
    environment_name: "env"
    project_path: "/home/{{deeksha }}/adcuratio"
    virtualenv_path: "{{/home/deeksha/setup-automation/adcuratio}}/{{env}}"
    alias_command: "alias adc='export SERVER_NAME=MASTER && export SERVER_DESC=MASTER && export DEBUG=true && export OPERATOR_ID=1 && source {{ env }}/bin/activate && cd {{ /home/deeksha/setup-automation/adcuratio }}/core-backend/'"

  tasks:
    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present

    - name: Create the virtual environment using virtualenv
      command: "virtualenv {{ /home/deeksha/setup-automation/adcuratio }}"
      args:
        creates: "{{ /home/deeksha/setup-automation/adcuratio }}/bin/activate"

    # Alternatively, you can use Python's venv module:
    # - name: Create the virtual environment using Python's venv
    #   command: "python3 -m venv {{ virtualenv_path }}"
    #   args:
    #     creates: "{{ virtualenv_path }}/bin/activate"

    - name: Activate the virtual environment
      shell: "source {{ env }}/bin/activate"

    # Install any required packages using pip within the virtual environment
    # For example, installing required dependencies:
    # - name: Install required dependencies inside the virtual environment
    #   pip:
    #     requirements: /path/to/requirements.txt

    - name: Add the alias to .bashrc
      lineinfile:
        path: "/home/{{ deeksha }}/.bashrc"
        line: "{{ alias_command }}"
        create: yes

    - name: Set the alias for the current session
      shell: "{{ alias_command }}"

    - name: Deactivate the virtual environment
      shell: "deactivate"
