- name: Create and set up Python Virtual Environment
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: pass
    user_name: "ubuntu"
    environment_name: "adcuratio-env"
    project_path: "/home/{{ user_name }}/adcuratio"
    virtualenv_path: "/home/{{ user_name }}/adcuratio/{{ environment_name }}"
    alias_command: "alias adc='export SERVER_NAME=MASTER && export SERVER_DESC=MASTER && export DEBUG=true && export OPERATOR_ID=1 && source {{ virtualenv_path }}/bin/activate && cd {{ project_path }}/core-backend/'"
  tasks:
    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present
    - name: Install python3 and python3-pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
    - name: Create the virtual environment using virtualenv
      command: "python3 -m venv {{ virtualenv_path }}"
      args:
        creates: "{{ virtualenv_path }}/bin/activate"
    - name: Activate the virtual environment
      shell: "source {{ virtualenv_path }}/bin/activate"
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ virtualenv_path }}/bin:{{ ansible_env.PATH }}"
    - name: Add the alias to .bashrc
      blockinfile:
        path: "/home/{{ user_name }}/.bashrc"
        block: "{{ alias_command }}"
        create: yes
    - name: Set the alias for the current session
      shell: "source /home/{{ user_name }}/.bashrc"
      args:
        executable: /bin/bash