- name: Download and Replace Files
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace configurations.py
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/configurations.py"
        dest: "/home/ubuntu/adcuratio/core-backend/engine/configurations.py"
      delegate_to: localhost

    - name: Replace swap_generation.py
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/swap_generation.py"
        dest: "/home/ubuntu/adcuratio/core-backend/engine/swap/swap_generation.py"
      delegate_to: localhost

    - name: Replace constants.py
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/constants.py"
        dest: "/home/ubuntu/adcuratio/core-backend/report/constants.py"
      delegate_to: localhost

    - name: Replace supervisord.conf
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/supervisord.conf"
        dest: "/home/ubuntu/adcuratio/core-backend/supervisord.conf"
      delegate_to: localhost

    - name: Replace epsilon_experian_scripts directory
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/epsilon_experian_scripts"
        dest: "/home/ubuntu/adcuratio/core-backend/refresh/epsilon_experian_scripts"
        remote_src: yes
      delegate_to: localhost

    - name: Copy local_configurations.py to engine directory
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/local_configurations.py"
        dest: "/home/ubuntu/adcuratio/core-backend/engine/local_configurations.py"
      delegate_to: localhost

    - name: Copy local_configurations_slave1.py to engine directory
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/local_configurations_slave1.py"
        dest: "/home/ubuntu/adcuratio/core-backend/engine/local_configurations_slave1.py"
      delegate_to: localhost

    - name: Copy local_configurations_slave2.py to engine directory
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/local_configurations_slave2.py"
        dest: "/home/ubuntu/adcuratio/core-backend/engine/local_configurations_slave2.py"
      delegate_to: localhost

    - name: Copy local_settings.py to adcuratio directory
      copy:
        src: "/home/ubuntu/ansible-playbook/backup/local_settings.py"
        dest: "/home/ubuntu/adcuratio/core-backend/adcuratio/local_settings.py"
      delegate_to: localhost
