- name: Create and set up Python Virtual Environment
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: pass

    user_name: "deeksha"
    environment_name: "env"
    project_path: "/home/{{ user_name }}/adcuratio"
    virtualenv_path: "/home/{{ user_name }}/setup-automation/adcuratio/{{ environment_name }}"

  tasks:
    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: present

    - name: Install python3 and python3-pip
      apt:
        name: ['python3', 'python3-pip']
        state: present

    - name: Create the virtual environment using virtualenv
      command: "virtualenv {{ virtualenv_path }}"
      args:
        creates: "{{ virtualenv_path }}/bin/activate"

    - name: Activate the virtual environment
      shell: "source {{ virtualenv_path }}/bin/activate"
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ virtualenv_path }}/bin:{{ ansible_env.PATH }}"

    # Install Python dependencies from requirements.txt
    - name: Install Python dependencies
      pip:
        requirements: "{{ project_path }}/core-backend/requirements.txt"
        virtualenv: "{{ virtualenv_path }}"

    # Continue with other tasks as needed

    # - name: Deactivate the virtual environment (if required)
    #   shell: "deactivate"
