


- name: Install and configure PostgreSQL
  hosts: all
  become: true

  tasks:
    # - name: Update apt cache
    #   apt:
    #     update_cache: yes

    - name: Install PostgreSQL and contrib packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Switch to postgres user and run psql command
      shell: |
        sudo -i -u postgres psql -c "CREATE USER minion WITH SUPERUSER PASSWORD 'alpha';"
        sudo -i -u postgres psql -c "CREATE DATABASE adcuratio WITH OWNER minion;"
        sudo -i -u postgres psql -d adcuratio -c "\q"
        sudo -i -u postgres psql -c "CREATE DATABASE demographics WITH OWNER minion;"
        sudo -i -u postgres psql -d demographics -c "\q"
        sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE adcuratio TO minion;"
        sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE demographics TO minion;"


