


 
  

#     

- name: Create a virtual environment and set up the alias
  hosts: all
  become: yes
  # become_method: sudo
  vars:
    # ansible_become_password: pass

  
    user_name: "deeksha"
    environment_name: "env"
    project_path: "/home/{{ deeksha }}/adcuratio"
    virtualenv_path: "{{ /home/deeksha/adcuratio}}/{{ env}}"
    alias_command: "alias adc='export SERVER_NAME=MASTER && export SERVER_DESC=MASTER && export DEBUG=true && export OPERATOR_ID=1 && source {{ virtualenv_path }}/bin/activate && cd {{ project_path }}/core-backend/'"

  tasks:
    - name: Create the virtual environment using virtualenv
      command: "virtualenv {{ /home/deeksha/adcuratio}}"
      args:
        creates: "{{ /home/deeksha/adcuratio }}/bin/activate"

    # Alternatively, you can use Python's venv module:
    # - name: Create the virtual environment using Python's venv
    #   command: "python3 -m venv {{ virtualenv_path }}"
    #   args:
    #     creates: "{{ virtualenv_path }}/bin/activate"

    - name: Add the alias to .bashrc
      lineinfile:
        path: "/home/{{ deeksha }}/.bashrc"
        line: "{{ alias_command }}"
        create: yes

    - name: Set the alias for the current session
      shell: "{{ alias_command }}"
