- name: Install Node.js v16.x
  hosts: all
  become: yes
  tasks:
    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
        state: present

    - name: Install Node.js
      apt:
        name: nodejs
        state: latest
        update_cache: yes
