---
- name: Install Yarn and Start Frontend
  hosts: all
  become: yes  # This is required to use sudo

  tasks:
    - name: Remove cmdtest
      apt:
        name: cmdtest
        state: absent

    - name: Remove yarn
      apt:
        name: yarn
        state: absent

    - name: Install Yarn using npm
      command: npm install -g yarn
      become_user: root

