---
- name: Install Node.js and Yarn
  hosts: all
  become: yes
  tasks:
    - name: Add NodeSource GPG key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Yarn
      apt:
        name: yarn
        state: present
        update_cache: yes

- name: Install frontend dependencies and start the server
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Navigate to frontend folder
      become: yes
      become_user: "ubuntu"
      command: cd /home/ubuntu/adcuratio/core-frontend/monolith/

    - name: Install frontend dependencies
      become: yes
      become_user: "ubuntu"
      command: yarn

    - name: Start frontend server
      become: yes
      become_user: "ubuntu"
      command: yarn start