# - name: Install Python dependencies from requirements.txt
#   hosts: all
#   gather_facts: false
#   become: yes
#   become_method: sudo
#   vars:
#     ansible_become_password: pass

  
#     user_name: "deeksha"
#     project_path: "/home/{{ user_name }}/setup-automation/adcuratio"
#     requirements_file: "/home/deeksha/adcuratio/core-backend/requirements.txt"  # Path to your requirements.txt file on the Ansible Controller

#   tasks:
#     - name: Copy requirements.txt to remote host
#       copy:
#         src: "{{ requir/home/deeksha/setup-automation/ansible-playbookements_file }}"
#         dest: "{{ project_path }}/requirements.txt"
#         mode: "0644"  # Set the correct file permissions for the copied file

#     - name: Install Python dependencies from requirements.txt
#       pip:
#         requirements: "{{ project_path }}/requirements.txt"
#  - name: Install Python dependencies from requirements.txt
#    hosts: all
#    gather_facts: false

#    tasks:
#     - name: Copy requirements.txt to remote host
#       copy:
#         src: "requirement.txt"  # Assuming the requirements.txt file is in the same directory as the playbook
#         dest: "/home/deeksha/setup-automation/adcuratio/requirements.txt"  # Path to the destination on the remote host
#         remote_src: yes  # This option indicates that the file exists on the remote host
#         mode: "0644"     # Set the correct file permissions for the copied file

#     - name: Install Python dependencies from requirements.txt
#       pip:
#         requirements: "/home/deeksha/setup-automation/adcuratio/requirements.txt"
# 
- name: Install Python dependencies from requirements.txt
  hosts: all
  gather_facts: false
  become: yes  # Add this line to elevate privileges
  become_method: sudo
  vars:
    ansible_become_password: pass

    # user_name: "deeksha"
    # project_path: "/home/{{ user_name }}/setup-automation/adcuratio"
    # local_requirements_file: "/home/ubuntu/my_ansible/ansible-playbook/requirements.txt"
    # remote_requirements_file: "{{ project_path }}/requirements.txt"
    user_name: "ubuntu"
    project_path: "/home/ubuntu/ansible-playbook/adcuratio/core-backend"
    local_requirements_file: "/home/ubuntu/ansible-playbook/requirements.txt"
    remote_requirements_file: "{{ project_path }}/requirements.txt"
  tasks:
    - name: Copy requirements.txt to remote host
      copy:
        src: "{{ local_requirements_file }}"
        dest: "{{ remote_requirements_file }}"
        remote_src: yes  # This option indicates that the file exists on the remote host
        mode: "0644"     # Set the correct file permissions for the copied file

    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: "{{ remote_requirements_file }}"
